### ISSUE TITLE
Avoid unconstrained sections in allocation networks

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1208]
As far as I can tell, there are now at least 2 cases of unconstrained sections in the allocation problem left:
- [ ] `FractionalFlow` nodes which are discussed [below](https://github.com/Deltares/Ribasim/issues/1208#issuecomment-1989556081);
- [x] `UserDemand` return flow is essentially an extra source. This leads to unconstrained behavior when collecting subnetwork demands, because if there is still return flow left when starting demand collection, flow can come from either the user return flow or the main network inlet. When collecting subnetwork demands flow should only be allowed to come from the main network inlet, to get a proper value for how much flow is required from the main network. Solving this might be as easy as setting user return flow capacity to 0 before starting demand collection. Yes, this means that some flow capacity is lost, but I find having an algorithm that is as deterministic as possible more important.

This is also as good a place as any to start using `max(0, JuMP.value(F[edge]))` everywhere when accessing flows, since they can be (very small) negative numbers.

**Comment by SouthEndMusic** [comment]
I forgot to bring up fractional flow in the meeting with the RTC-Tools team, but I realised that this can also be solved nicely with buffers. That is: use equality constraints for the relationship between the inflow and the outflow for each of the fractional flow branches, and store flow that cannot immediately be used in one of these branches in a buffer. 

Note that this can lead to situations where a lot of flow ends up unused in these buffers, but I would call that a schematization issue.

**Comment by gijsber** [comment]
Hi @SouthEndMusic : are you saying.. if a user has two outgoing edges, one with fraction 0.5 and one with fraction 0.4, you basically buffer the 0.1 portion to keep your optimization problem sane.
It is the modellers problem that the fractions do not add up to 1.0.

Now I wonder two things:
1. what happens if the modeller has defined fractions of 0.5 and 0.6 (total > 1)
2. Do we have a validaton rule that actually detects that fractions do not add up to exactly 1 ?

**Comment by gijsber** [comment]
Hi @SouthEndMusic , 

For `UserDemand` I agree with you solution as given in the issue description.
For `FractionalFlow` @SnippenE  and me concluded that we indeed have to follow the fractional flow division (as this is what the physical layer will follow), which results in B potentially missing out on water that is requested.

If modellers are unhappy, they need to consider if they have other solutions instead of fractional flows.
If we really end up in undesirable sitautaions, we may decide to update the algorithms at a later stage, e.g. as follows:
1. the fractionalflow division gets a priority and becomes a goal in the optimization (instead of a onstraint), where we try to minimize the deviation from this division.
2. the resulting fractional division then needs to be enforced via control on the fractional flow nodes.
