### ISSUE TITLE
Support specifying coordinate reference system (CRS) of geometries

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1254]
**What**
It is currently not possible to specify a CRS for our spatial tables. That means we cannot reliably place our geometries on top of a map.

**Why**
A clear and concise description of why this feature is needed and its context.

**How**
I think it'd be best to specify the CRS once when constructing the Model object, and then setting that preferably directly during GeoDataFrame construction. Setting it on `to_file` works for the GeoPackage, but it'd be nicer if we can also plot from Python on basemaps before writing to file.

~~CRS should be optional since maybe the true CRS is unknown, or there is no true CRS, like with most our test models. This unfortunately gives a warning from pyogrio that we currently suppress. Hopefully we can stop doing that. If this global suppression affects other Python code it would be best to only do that temporarily when calling `to_file` using [this](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings).~~ EDIT: Let's make it required, see post below.

**Additional context**
https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.set_crs.html
https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.to_file.html
https://github.com/Deltares/Ribasim/blob/e1f8b81d861b62724d8fb9ccf8b828fa8e68ff32/python/ribasim/ribasim/input_base.py#L41

**Comment by Huite** [comment]
I think you could seriously consider making the CRS required for Model initialization.
Preferably this doesn't introduce any additional attributes, but just forwards it immediately to the geodataframes.

The QGIS plugin always sets a CRS based on the current Map Canvas: https://github.com/Deltares/Ribasim/blob/1f20b68eb4a6cba52fda7b51fe3f5ba5cfae9edf/ribasim_qgis/widgets/ribasim_widget.py#L72

QGIS defaults to EPSG:4326 (WGS 84) -- although I personally set my default QGIS CRS to EPSG:28992.

Although in that case, it makes some sense to support `to_crs` and `set_crs` methods on the Model object as well (they just forward to the geodataframes). Otherwise you have to do it twice yourself on the node and edge dataframe.

**Comment by visr** [comment]
Yes that is a good point, let's make it required input.
