### ISSUE TITLE
Test same node ID for different node types

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1262]
With #1113 we theoretically support having e.g. both `Basin #5` and `Pump #5` in the same model. Now that #1110 is merged, we should test that this works properly.

Related to #1256.

**Comment by SouthEndMusic** [comment]
I suggest adapting the `main_network_with_subnetworks` model for this as it covers a lot of ground. 

A Question about a crashing simulation by Josje van Houwelingen (does she have a Github account to tag?) also pointed out that the sparse `capacity` matrix (see mainly `allocation_init.jl`) uses node ID numbers as indices directly, which isn't valid anymore already since the introduction of the `MetaGraph`. Would a dictionary be a good replacement here, or is there some sparse matrix object which allows generic index sets?

**Comment by visr** [comment]
> would a dictionary be a good replacement here, or is there some sparse matrix object which allows generic index sets?

It's worth checking if we can use this:

https://jump.dev/JuMP.jl/stable/manual/containers/#SparseAxisArray
https://jump.dev/JuMP.jl/stable/api/JuMP.Containers/#JuMP.Containers.SparseAxisArray

**Comment by SouthEndMusic** [comment]
@visr I also have to make a `get` method which calls `get` on the wrapped dictionary, because accessing missing values is not supported on `SparseAxisArray`.

**Comment by SouthEndMusic** [comment]
I realized that I don't actually need that `get` method after all, see https://github.com/Deltares/Ribasim/pull/1330/commits/0229364c4c4545d247f9c21bf0e25facae29b7b6. Keeping the use of the array interface in `allocation_init.jl` is nice 👍
