### ISSUE TITLE
UserDemand: make demand and allocated Matrix{Float64}

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#1277]
These fields are currently initialized as a single long vector and a vector of vector. 

```julia
demand = zeros(n * length(priorities))
allocated = [fill(Inf, length(priorities)) for id in node_ids]
```

Having them as matrix would be nicer.

```julia
demand = zeros((n_priority, n_user))
allocated = fill(Inf, (n_priority, n_user))
```

This should work fine with the BMI as well.

**Comment by visr** [comment]
For BMI it seems we should offer one dimensional arrays. I only started doing that when someone pointed me to the best practices in https://github.com/csdms/bmi-example-julia/pull/5. Still I don't get the row/column-major indexing reason, since flattening it does not resolve that.

However, just like the linked PR we can use a Matrix internally, and only towards the BMI offer it in 1D, that `vec` call is just a different view on the same memory.

**Comment by Huite** [comment]
I guess you're automatically forced to think about row/column-major array on the receiving part if it's a flat array.

We can reconstruct it into a 2D array in imod_coupler anyway using `.reshape()`.
