### ISSUE TITLE
imod timeseries plugin shows edge_id as float

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#1320]
The flow.arrow contains flow on the basins, with the edge_id as NaN for non-edge flows. The imod plugin does a groupby operation with  the edge_id. During reading, the NaNs mean that the edge_id is float-encoded.

Would be fixed if this specific table doesn't contain the "vertical" flows.

Alternative is to filter away these rows in the `read_arrow` function.

**Comment by visr** [comment]
Yes we will remove both `edge_id` (https://github.com/Deltares/Ribasim/issues/1310) and the "vertical" flows from flow.arrow, either would fix this.

**Comment by Huite** [comment]
Alright -- great, then no changes in the QGIS plugins are required.

**Comment by visr** [comment]
Not sure why, but this is fixed now:

![Image](https://github.com/user-attachments/assets/aff5e026-99a4-488f-8666-66de15acd4a7)

Technically the greyed out ID column should read "edge_id" not "fid", since the name of the primary key column in the Edge table is "edge_id". GeoPackage doesn't require that it is called "fid".
