### ISSUE TITLE
Document TeamCity pipeline

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#1331]
The TeamCity configuration doesn't change too often, so we could dedicate a part of our documentation to describe it.

- Make a mermaid diagram of its pipeline
- Document its function in text form

**Comment by Jingru923** [comment]
- People to understand what is included in the ribasim suite.
- People to know how our testing pipeline works, what do we test

**Comment by Jingru923** [comment]
Github Actions:
- Julia Run Testmodels (Run generated testmodels on multiple platforms and check if they ran successfully, but don't check output)
- Julia Tests (Run Julia tests on multiple platforms, depends on generated testmodels)
- Docs (Executes our documentation examples)
- Pre-commit (Checks code quality with linters)
- Python codegen (Check that codegeneration wouldn't change any files -> it is up-to-date)
- Python lint (Run mypy on our Python codebase) TODO: Rename "Python Lint" to "Mypy" and "python_lint.yml" to "mypy.yml"
- Ribasim Python tests (Run Ribasim Python tests on multiple platforms and multiple Python versions, depends on ribasim_testmodels)
- QGIS Tests (Run QGIS tests, very limited at the moment)

**Comment by Jingru923** [comment]
When use TeamCity instead of GitHub Actions?
- takes a long time to run
- other TeamCity projects depend on artifacts
- release needs artifacts

TeamCity:
- Generate Testmodels (artifact is part of the release)
- Make GitHub Release (uses artifacts and makes release)
- Build libribasim - Linux and Windows (artifact is tested and used by iMOD Coupler)
- Build ribasim_cli - Linux and Windows (artifact is tested and used by release)
- Test ribasim_api - Linux and Windows (tests libribasim artifact)
- Test ribasim_cli - Linux and Windows (tests ribasim_cli artifact)
