### ISSUE TITLE
Allocation based on equal ratio

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#1348]
**What**
Allocation should be done with equal ratio among demands with the same priority.

**Why**
As requested/agreed upon at TKI-workshop (April 2,2024)

**Comment by SouthEndMusic** [comment]
This amounts to switching to the `linear_relative` objective function from https://github.com/Deltares/Ribasim/pull/751. Are we sure we don't want to have the option for objective functions back? Maybe let the modelers experiment with them?

**Comment by Huite** [comment]
I think almost every hydrologists wants this ratio based approach 99% of the time.

If you don't find that convincing: anything that is undefined is not a usable objective function. The reason is that it breaks the reproducibility of your simulations. If I have user A and user B with the same priorities and the objective function is equally happy with the following results:

* A 100% B 0%
* A 50% B 50%
* A 0% B 100%

It will pick one seemingly "at random" (behind the scenes maybe based on node number of graph traversal order or whatever).

This could mean that if you remove node A, change your mind and add it again, maybe it will now "randomly" prioritize the other one instead.

**Comment by visr** [comment]
Wait, yesterday I also thought what was suggested was the same as switching to `linear_relative`. But that merely implies that it is the fraction that counts, not that it is the same fraction for everyone in the same priority. The same fraction is indeed nicer, and more constrained.

For `linear_relative`, if A and B have the same demand and priority, my understanding is that all three of @Huite's bullets are still the same value, which we want to avoid.

**Comment by SouthEndMusic** [comment]
@Huite I completely agree that the problem should be fully constrained and in some abstract sense continuous, in that small changes to the model should lead to small changes in the allocation outcome. The current objective function indeed has a problem in that regard.

@visr you are right, but we are heading back to the discussions we had about fair distribution of flows much earlier on in the allocation discussions. You are essentially talking about maximizing the minimum fraction allocated, but that has its own flaws. The problem there is that the optimizer doesn't care about bringing more flow to some user unless it can raise the allocated fraction of all users.

I think the `quadratic_relative` objective function steers towards this fair fractional distribution. It might be worth another shot getting this to work reliably, especially now that we use a newer version of HiGHS.
