### ISSUE TITLE
PoC: Testbench for model integration tests

### ISSUE THREAD

**Issue by SnippenE** [Deltares/Ribasim#1412]
We need to develop a test bench that can run real models developed in the TKI-project/LHM-project for the NL and future international cases. 

Start with the HWS model, the test bench should be able to check:
- if model code breaks running models
- impact on results for changes in model code
- impact on performance for changes in model code
- (new add) the test bench should show information of the performance 

Linked to some relevant issues that have information on performance of the current solution:
#319 is an issue to investigate binary size
#545  is an issue that stated HWS runs a year in ten minutes
#462  #151  benchmark different solver

**Comment by Jingru923** [comment]
I have updated the description, the goal of #1471 is now also part of the scope.

**Comment by Jingru923** [comment]
For checking if model code breaks running models, this can be done by simply running the model and see if run fails. 

As for the impact on results for changes in model code, I suggest to have a benchmark for basin end states. There are 134 basins, in the model, the output file `basin_state.arrow` looks like something that we can use as benchmark. I expect that this benchmark will need to be updated from time to time because HWS model is changing. For now, we can use the output file `basin_state.arrow` from `hws_2024_7_0` as a benchmark.

_For performance check, coming up soon_

**Comment by Jingru923** [comment]
Update on performance check:

I set up a limit of 10 minutes runtime. If the second run of the model (after the precompiling and the first run) takes more than 10 minutes, test would report fails. 

Are there more things should be reported?
