### ISSUE TITLE
v2024.7.0: PydanticSchemaGenerationError and ValidationError

### ISSUE THREAD

**Issue by harm-nomden-sweco** [Deltares/Ribasim#1416]
when importering new ribasim version, I get a PydanticSchemaGenerationError, 
It works when I add     `model_config = ConfigDict(arbitrary_types_allowed=True)`    to the class SpatialTableModel

Maybe related to this adjustment: when initiating a model with: 
```
model = Model(starttime="2020-01-01", endtime="2021-01-01", crs="EPSG:4326")
```

I receive:
```
ValidationError: 1 validation error for Model
  Value error, Unknown column geometry [type=value_error, input_value={'starttime': '2020-01-01...01', 'crs': 'EPSG:4326'}, input_type=dict]
```

**Comment by visr** [comment]
Do I understand correctly that without any changes to the SpatialTableModel, this fails for you on "Unknown column geometry"?

```python
from ribasim import Model
model = Model(starttime="2020-01-01", endtime="2021-01-01", crs="EPSG:4326")
```

What pydantic and pandera versions are you using?
We are using pydantic 2.6.4 and pandera 0.18.3.

Possibly we need to require at least [pandera 0.18](https://github.com/unionai-oss/pandera/releases/tag/v0.18.0) in our Conda recipe, since it seems that is the version that added GeoDataFrame support.

https://github.com/conda-forge/ribasim-feedstock/blob/ace759fb6dcafb3b2d0da81e976d1d85cd7e8fbf/recipe/meta.yaml#L28

**Comment by harm-nomden-sweco** [comment]
Indeed working fine with pandera 0.18... Thanks!
