### ISSUE TITLE
Ribasim v2024.7.0 not working with old ribasim.toml files

### ISSUE THREAD

**Issue by Joris-J** [Deltares/Ribasim#1422]
I'm using the newest release of ribasim (v2024.7.0) to read a previously made ribasim.toml.

ribasim.Model.read(r"file_path/ribasim.toml")

I get a validation error:

_ValidationError: 1 validation error for Model
crs
  Field required [type=missing, input_value={'starttime': datetime.da...m_primary/ribasim.toml'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing_

I've attached the toml-file to this post ([ribasim_primary.zip](https://github.com/Deltares/Ribasim/files/15078821/ribasim_primary.zip)). 
I do not have this issue in v2024.6.1

**Comment by visr** [comment]
Thanks for the report. This is an intentional breaking change in v2024.7. At this point old TOML files are not guaranteed to work with newer Ribasim versions. The validation error for `crs` that is mentioned is a new required key in the TOML. For a Dutch model, you probably want to add

```toml
crs = "EPSG:28992"
```

to the TOML file.

https://deltares.github.io/Ribasim/core/usage.html#configuration-file

There are also breaking changes to DiscreteControl in the same release. We should still update the release notes in https://github.com/Deltares/Ribasim/releases/tag/v2024.7.0 to highlight these, ideally with update instructions.

**Comment by visr** [comment]
I updated the release notes and breaking changes in https://github.com/Deltares/Ribasim/releases/tag/v2024.7.0 with more information. Let us know if you have trouble upgrading to the new version. I'll close this issue for now.
