### ISSUE TITLE
Models with (multiple) discrete control(_states) raise exceptions

### ISSUE THREAD

**Issue by DanielTollenaar** [Deltares/Ribasim#1567]
**What**
Models with (multiple) discrete control raise exceptions in ribasim 2024.8.0.

For the Ribasim RWS-HWS model we are trying to build-in `verdeelsleutels`; discrete control controlling fractions between basins depending on upstream discharges. We have two `Lobith` controlling discharge over Rhine branches and `Monsin` controlling Meuse discharge over lower Meuse and canal systems.

**Reproduction**
We increased complexity starting with a model without control 1 untill crashing models 3 and 4. Except controls the rest of the models is the same:
1. Model without verdeelsleutels (no control), works, see: https://we.tl/t-VE2QSqci24
2. Model with `Lobith` only, works as well, see: https://we.tl/t-LDyMnJXCia
3. Model with `Monsin`only, raises an Exception: https://we.tl/t-uW9usryf0C
![image](https://github.com/Deltares/Ribasim/assets/14051252/7a512b63-cb75-421f-a5a4-6244beea63d5)
4. Model with both `Monsin` and `Lobith`, raises another Exception: https://we.tl/t-St9vuGqJZO
![image](https://github.com/Deltares/Ribasim/assets/14051252/aaf3fc2d-fcc4-4c9c-ac57-dbdf402c7f47)

Issue 3 we cannot follow; it seems to pass the validator, but than doesn't give any info. At 4, it seems the validator get's messed up with different control_states; it seems to expect control_states of Monsin at Rhine-fractions and vise-versa. As:
- Node 7124 of the Exception is the Outlet at Monsin
- The connected DiscreteControl node = 1000001 has only control_states with pattern `Monsin_###`. 
- FractionalFlow nodes 10653 and 7137, downstream Outlet 7124 have only control_statesw ith pattern  `Monsin_###`

**Comment by gijsber** [comment]
good to keep #720 in the back of your mind

**Comment by visr** [comment]
See #1569 for a fix to the validation code that triggered point 4.

Point 3 is a more difficult issue. It is thrown due to this TODO: https://github.com/Deltares/Ribasim/blob/0c19719ea764499495dad4af003f640587382376/core/src/solve.jl#L619

If you replace the Outlet with a Pump it should work. This is because the Pump will always move a 1Q over a FractionalFlow to fractions of say 0.4Q and 0.6Q.

The Outlet reduces the flow to 0 if the downstream level approaches the upstream level. But what are we supposed to do in the FractionalFlow if one path is blocked or reduced in this way? Should we give up on the fraction and just send it where it can go? Right now the assumption in the FractionalFlow is that the upstream side alone determines Q, and FractionalFlow only has to take fractions off.

**Comment by DanielTollenaar** [comment]
Check, I'll change to a fake TabulatedRatingCurve for now as it should go to a real-one, in time, any way. Two questions:
- Could it be [Connectivity](https://deltares.github.io/Ribasim/reference/validation.html#connectivity) needs an update?FractionalFlow doesn't seem to be allowed downstream TabulatedRatingCurve either.
- As we see it as a connectivity-problem, would it be an enhancement to capture this in data-validation?

**Comment by visr** [comment]
Yeah good points, I added #1570.

You mean changing it to two TabulatedRatingCurves one one Basin? Right now one TabulatedRatingCurve to two FractionalFlow also works, but if we stop it from sending water to higher downstream levels that will have the same issue.
