### ISSUE TITLE
Generate Testmodels pipeline needs fixing 

### ISSUE THREAD

**Issue by Jingru923** [Deltares/Ribasim#1631]
This pipeline has been failing for days. I communicated with TopOps and they have investigated and some possible solutions are provided. 

The artifact of this pipeline will be used for release. Therefore this should be fixed before our next release.

**Comment by visr** [comment]
What are the possible solutions? The issue is that the disk is full, right?

**Comment by Jingru923** [comment]
I got replies
> 'Your pixi problems are due to  the fact that pixi is using /home/svc-teamcity-ansible/.cache as a default for caching stuff, which is very quickly filled because the .cache directory is also shared with java,  matlib, and others.

Things to do:
 
- Yesterday we have enlarged /home/svc-teamcity-ansible from 2 GByte to 4 GByte, so that is something.
- We are planning to make a clean script which just removes the content of the .cache directory. As far as I know (but maybe you know this better) there is no way with pixi to clean the cache after  processing. The script can be run  during nightfall automatically and doesn't do anything more than rm -rf /home/svc-teamcity-ansible/.cache/*.
- You can set a environment variable PIXI_CACHE_DIR  to write the cache somewhere else. For example: /u/svc-teamcity-ansible/.cache should be a location with more than enough space. We can enforce this by putting this in  the standard enviroenment of svc-teamcity-ansible, but maybe you can try to add this to one of your projects

**Comment by visr** [comment]
For reference, these are the Pixi caching docs: https://pixi.sh/latest/features/environment/#caching

I just had a look locally, and my `cache/pkgs` folder was 50 GB with 1 million files. Most of it is older versions of packages we don't use anymore. Since we update our pixi environment monthly, I guess for us it would make sense to clear the cache monthly as well. Clearing it nightly would make it re-download all our dependencies every day, which may also not be desired. Or are the images wiped monthly anyways?

Are both `/home/svc-teamcity-ansible/.cache` and `/u/svc-teamcity-ansible/.cache` for a single agent, but shared between jobs? Setting PIXI_CACHE_DIR to this location may be a good option.

**Comment by Jingru923** [comment]
Now DevOps team added a softlink from /home/svc-teamcity-ansible to /u/svc-teamcity-ansible which temporarily solves the problem. Both /home/svc-teamcity-ansible/.cache and /u/svc-teamcity-ansible/.cache are shared between jobs. We should look into how to clear the cache periodically.

**Comment by Jingru923** [comment]
Talked to Akhil, this issue can be temporarily closed.
