### ISSUE TITLE
QGIS: Show data for selected nodes

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1648]
In QGIS you can select one or more nodes:

![image](https://github.com/user-attachments/assets/5885cba4-b815-46fe-b89a-f9ecc36ab9df)

This can be used to show the Node table for those nodes:

![image](https://github.com/user-attachments/assets/441cfebc-ba7b-4c1d-88be-6e23710135bb)

However, if you want to see the data associated with this node, you need several extra steps. For instance, open the "Basin / profile" table, apply a field filter on `node_id`, and enter the node ID you selected manually.

![image](https://github.com/user-attachments/assets/da22283e-4981-4604-9bcf-a259fbebc7ce)

Ideally a user can directly see and edit all data for a selected node. Perhaps we can for a node of type X, automatically apply a field filter on all tables `X / *` to show this. Or perhaps some other way that integrates nicely with existing QGIS functionality exists? Like perhaps automatically doing some kind of joins between these tables.

It looks like this would also be needed for #790.

**Comment by deltamarnix** [comment]
We are looking for QGIS joining and relations: https://docs.qgis.org/3.34/en/docs/user_manual/working_with_vector/joins_relations.html#setting-relations-between-multiple-layers

I did some small tests. joining is nice when there is a 1-to-1 relation between features in different layers. For example: Basin / state or Basin / area.

I made a model and added Basin / area and Basin / state. Then I set a Joins property on the Basin / area layer. When I then create a layer, and fill in the node_id, it automatically matches the node_id and gives me the information about the node. And I also tried it the other way around. On Node I set a relation to Basin / state, and when you add a new node, it will automatically add a row in the Basin / state if it's not there.

![image](https://github.com/user-attachments/assets/c6d87f14-f2af-4f3b-b4f8-947f27bf765a)
![image](https://github.com/user-attachments/assets/8408cf6e-487b-48c8-a14b-f05225f0dc41)
![image](https://github.com/user-attachments/assets/4aa0f0ea-fb86-45ba-835b-1f46781b2ee0)

The other option is useful for 1-to-N relations, like Basin / time. Then it's better to use relations and it looks more like this:

![image](https://github.com/user-attachments/assets/4c62a7aa-e271-4c02-8e89-ce30b4807742)

Both joins and relations are stored in QGIS project files, which means that we have to initialize all those relations every time we will open a toml file. The other option is that we start working with QGIS project files and let users open their projects that way, instead of the Open button in the Ribasim plugin.

**Comment by Huite** [comment]
Oh, the relations thing looks very good! Does it provide a good table view as well?

That is, what if you click this button:

![image](https://github.com/user-attachments/assets/39d51139-4a37-452b-95a5-9b0861d45f67)

**Comment by deltamarnix** [comment]
Clicking that button will just bring you to the table I guess.

Another option would be to add relationship tables with SQL queries inside of the geopackage. In that way it is not stored in a qgis project, but in the geopackage itself.

**Comment by Huite** [comment]
A possible risk with storing it inside of the geopackage is that QGIS / OGR will not be smart enough to see through it when it matters.

For example, if you have transient data associated with vector features, one way to make it known to QGIS is by simply duplicating the geometries for each timestamp. This has the unfortunate downside of making QGIS quite slow to draw the vector features. The reason is that it's filtering over **all** features whenever you pan the map view to decide which ones to show.

**Comment by deltamarnix** [comment]
More information:

- https://gis.stackexchange.com/questions/482335/how-to-store-relationships-in-geopackage-with-qgis
- https://github.com/qgis/QGIS/pull/49504

**Comment by Huite** [comment]
Looks like the second link disproves my guess! That would be excellent news and we would able to keep everything contained in a geopackage.

**Comment by evetion** [comment]
- [ ] Ideally we implement relationships in gpgk (manually writing those tables) as described here https://docs.ogc.org/is/18-000/18-000.html
- [ ] Test and document how this works in QGIS

**Comment by evetion** [comment]
So there are roughly three paths for getting the relationship info in QGIS:
- Implement foreign keys in SQLite and use discover relationships in QGIS
- Use the GPKG relation extension and populate all the required N-N tables.
- Make the relationship in QGIS (only)

I like the first option, but SQLite tables can't be altered after creation, so I need to generate the SQL statements myself. I've got it working for pure pandas (so all non-spatial tables), but spatial tables is another beast (ogr generates the schema, not pandas). Besides, it would require duplicating the functionality in PyQGIS (even harder) for all models created there. Still, we might even keep the non-spatial tables foreign key creation in Python, it makes the GPKG "better" imho.

However, I now implemented the third option, which works pretty well. I haven't yet found a way to quickly filter the attribute table, but this is already useful and should be merged:

Identification results


![Image](https://github.com/user-attachments/assets/6a961402-279b-479d-ad32-8734689bf52f)




Form with table view (as asked by @Huite above


![Image](https://github.com/user-attachments/assets/821e70c5-dfb3-49c7-b32d-2dd3f6f732a3)

**Comment by evetion** [comment]
Now attribute tables also work with Node selection. 
![riba_select](https://github.com/user-attachments/assets/074c1f58-926b-4d5e-a640-86a5a746a4c2)

Note it needs a fix for the Edge (it has two relationships), as only the (last) to_node_id is selected, not selecting all related edges.
