### ISSUE TITLE
Fix Delwaq CI

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1668]
I hoped https://github.com/Deltares/Ribasim/pull/1664 would fix it, but it did not.
https://github.com/Deltares/Ribasim/pull/1649 may also be related.
Delwaq seems to segfault, so not really a helpful error there.

**Comment by deltamarnix** [comment]
The error that I see is QGIS plugin manager breaking down because it cannot decode some character. I think we should not install QGIS and its plugins for testing DELWAQ.

**Comment by Jingru923** [comment]
I tried to run without QGIS plugin by `pixi run install-ci`, the pipeline returns error during unit testing 
```
Pixi task (delwaq in dev): pytest python/ribasim/tests/test_delwaq.py
```  

I think we should check if we can run delwaq coupling on our machine successfully.

**Comment by evetion** [comment]
Had a nice investigation with @mKlapwijk about this. Turns out that newer Delwaq versions crash on logging to screen in specific cases (ours, and laptop, but not on their TC projects!): https://issuetracker.deltares.nl/browse/DELWAQ-881. For now, I'll revert to an older Delwaq version, we can expect that the next (weekly) pinned build of Delwaq has workarounded/fixed this issue.
