### ISSUE TITLE
Investigate convergence options

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#1700]
Adding backtracking in the nonlinear solver settings (https://github.com/Deltares/Ribasim/pull/1697) gave a huge speedup, probably because the convergence of the nonlinear solver is much faster. To get more insight into this speedup, we can look at the difference in solver stats (an output file for this was introduced in https://github.com/Deltares/Ribasim/pull/1677).

Now that we have this speedup, we should also re-asses the other convergence measures we have in place:
- Reduction factor (with magic hardcoded threshold values)
- `isoutofdomain`. We probably want to keep this, but it's good to know whether it still being triggered sometimes

Also, we still might need [this](https://github.com/Deltares/Ribasim/issues/1414#issuecomment-2231071299) for depleting basins.

**Comment by Huite** [comment]
> Reduction factor (with magic hardcoded threshold values)

As I mentioned in chat, I think you're still going to need those. Even though e.g. EulerImplicit is unconditionally stable, you will either get very small time steps (with adaptive time stepping) or poor convergence (fixed time step).
To illustrate with evaporation:

$$
    Q_{ET} = 
    \begin{cases}
        ET * \text{area}, & \text{if } S > 0 \\
        0, & \text{if } S = 0
    \end{cases}
$$

Any time a droplet of water comes in, $Q_{ET}$ immediately jumps to its maximum value and depletes storage.
For extraction, it's similar to turning your pump in the ditch on when you see the first droplet of rain (which is why I say it's physically implausible too).

The adaptive timestepper notices this so $\Delta t \to 0 $.

Alternatively, with fixed time step it'll have trouble converging because $Q$ is switching on and off between Newton iterations.

`isoutofdomain` is probably good to keep around for if you want to keep the option supporting solvers with less stability guarantees?
