### ISSUE TITLE
Use of `fid` column in Geopackage

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1718]
The `fid` column is mandatory (by SQLite) as a unique key for each row. By default it is set to autoincrement if not defined.

Our usage in Ribasim is inconsistent, we always set it (1:n) on writing, but it does not equal the node_id. However, for the edge table, it *is* used (implicitly) as our edge_id key.

Possibly solutions;
- Use fid as node_id key
- Add edge_id back

I'm inclined towards the latter. fid is a file format specific thing, and depending on the tooling is hidden/ignored (geopandas silently ignores any existing fid column).

Relates to #1717

**Comment by visr** [comment]
I'm inclined to store our IDs in the `fid` column. We are required to have one anyway, and it exactly meets our requirements for our IDs. If we don't we have two ID columns, which can lead to confusion between the two. In #1717 I see you propose putting our IDs copied as fid values, but that can start running out of sync if people start editing in e.g. QGIS.

Geopandas indeed requires passing `fid_as_index = True`.

Right now we are not consistent between Edge, where we use `fid`, and Node, where we don't. This should be consistent.

Right now edge IDs cannot be explicitly set, meaning that they are never stable. Allowing optionally setting the edge ID just like #1717 does for node ID would make it fully consistent.

**Comment by visr** [comment]
> The fid column is mandatory (by SQLite) as a unique key for each row.

This isn't quite accurate, from the GeoPackage spec: "_A feature table SHALL have a primary key column of type INTEGER and that column SHALL act as a rowid alias._"

We'd have to test how well this is supported by GDAL/QGIS/geopandas, but we could just set `node_id` as the primary key for the Node table and set `edge_id` as the primary key for the Edge table. Then we don't need `fid` at all.

The non-spatial tables (`Basin / static` etc) also get an `fid`, that falls outside our data model but was needed to make the tables editable in QGIS. This was done in https://github.com/Deltares/Ribasim/pull/873. To avoid confusion, Marnix tried to hide these columns in https://github.com/Deltares/Ribasim/issues/841#issuecomment-1842885072 but ran into a QGIS bug that has since been fixed. So we should try again to hide these columns for non-spatial tables.

We also shouldn't forget to adjust this code that currently copies `node_id` over to `fid`: https://github.com/Deltares/Ribasim/pull/1717#discussion_r1715089917
