### ISSUE TITLE
Validate node types and number of edges when adding a new edge.

### ISSUE THREAD

**Issue by evetion** [Deltares/Ribasim#1752]
By either linking (templating) or copying from the core code.

DoD:
When run the model in python, error is given.

**Comment by Jingru923** [comment]
Checking the minimum neighbor amount of a node seems not possible with current setting.

At the moment I verify the maximum neighbor amount in the `add` function of `model.edge`. But it is not possible to verify if the neighbor amount the minimum amount if the model is incomplete.

Verifying it when the model is complete is no longer possible because our edge table now no longer contains `from_node_type` and `to_node_type` but verifying the neighbor amount require this information. 

If there is better solution, please let me know. For now I will looking into how to automate the connectivity table generation
