### ISSUE TITLE
Consider adding `min_upstream_level` and `max_downstream_level` to Pump and Outlet

### ISSUE THREAD

**Issue by DanielTollenaar** [Deltares/Ribasim#1771]
Currently a Pump will drain the upstream Basin until it's empty. I don't know a surface water example where this occurs (in sewers it does). The idea of a pump is in >90% of the cases to maintain a certain `upstream_target_level` and switch off if that level is reached.

Some pumps also switch off if a `downstream_target_level` is exceeded in case of flooding (maalstop) or water supply.

If this could be implemented in Ribasim we could drop quite some PID or Discrete Control Nodes.

@rbruijnshkv, what is your experience, opinion with/on this?

Edit:

- [ ] Pump: `min_upstream_level`
- [ ] Pump: `max_downstream_level`
- [ ] Outlet: `min_upstream_level` (rename `min_crest_level`)
- [ ] Outlet: `max_downstream_level`
- [ ] TabulatedRatingCurve: `max_downstream_level` (moved to #1789)

**Comment by SnippenE** [comment]
Discussed with Martijn: saves time in development Ribasim-NL and fit within the initial sprint planning

**Comment by visr** [comment]
Here's a proposal, would like to hear from @DanielTollenaar and @rbruijnshkv if they think this sufficiently covers this use case:

Pumps and Outlets both need to stop as the upstream level gets too low, and stop as the downstream level gets too high.

I don't think using `target` in the new parameter names is a good idea, that to me suggests that it tries to reach this level from both sides, which it doesn't. PidControl has `target`.

Currently only Outlet supports upstream too low via `min_crest_level`. This is done via a reduction factor, such that it smoothly goes to 0 as it approaches `min_crest_level`. This smooth reduction factor will probably help the solver compared to a discrete step to 0 flow as DiscreteControl would do this. Also since Outlet is gravity-based it supports stopping if the downstream level exceeds the upstream level. Adding a maximal downstream level on top of that makes it more flexible.

How about these parameters:

Pump: `intake_level`
Pump: `max_outlet_level`
Outlet: `crest_level` (rename `min_crest_level` since IMO the `min_` is superfluous)
Outlet: `max_downstream_level`

I'm avoiding using the term `downstream` and `upstream` for Pump since it can be confusing if it Pumps water back upstream.

Are other parameters needed? I can imagine TabulatedRatingCurve: `max_downstream_level` could also be useful. Like Outlet the TabulatedRatingCurve is also gravity-based.

**Comment by DanielTollenaar** [comment]
Can live with dropping `target_`, I derived it from streefpeil. Both `Pump` and `Outlet` are highly conceptual in Ribasim; with Rijkswaterstaat we had some confusion on `min_crest_level` as we used `streefpeil` and not an actual level of a crest of a weir.

What if you use `min_upstream_level` and `max_downstream_level` for `Pump`, `Outlet` and `max_downstream_level` for `TabulatedRatingCurve`? These names can be used generic in all types of nodes when applicable and always mean the same.

**Comment by rbruijnshkv** [comment]
Great to hear that it will be implemented.

It's important to be able to make the distinction between water supply and water drainage structures. This function determines the control, which goes further than just an upstream and downstream water target level. Could this be added as well?

**Comment by visr** [comment]
> These names can be used generic in all types of nodes when applicable and always mean the same.

Indeed consistent names are convenient and easy to understand, and match the conceptual level better. That is probably more important than my point about upstream/downstream confusion for Pump.

Pump: `min_upstream_level`
Pump: `max_downstream_level`
Outlet: `min_upstream_level`
Outlet: `max_downstream_level`
TabulatedRatingCurve: `max_downstream_level`

> Could this be added as well?

@rbruijnshkv I don't understand, could you describe in more detail what you'd want to add?

**Comment by BdGraaff** [comment]
I think 95% or more of the pumps ('gemalen') in regional systems can be classified in two categories:

1. **Drainage pumps ('afvoergemalen')**: These pumps discharge excess water from the upstream basin ('peilgebied'). They switch on if the upstream water level is above the switch on level ('aanslagpeil'). They switch off if the upstream waterlevel is below the switch off level ('afslagpeil'). If they discharge in a regional reservoir ('boezem') they can also be switched off if the downstream water level reaches a maximum allowable level ('maalstoppeil'). This is to prevent failure of the embankments along the regional reservoir. Drainage pumps can also be used to flush water ('doorspoelen') through the water system in order to keep the water fresh. In most cases there is no special control for this in the drainage pump. Inlets are tuned in such a way that excess water reaches the pumps and the switch on level is exceeded. The pump will discharge the excess water.
2. **Irrigation pumps ('aanvoergemalen')**: The main function of these pumps is to supply water to the downstream basin when the water level in the downstream basin drops below the minimum level or switch on level. The pump stops supplying water when the water level in de downstream basin exceeds the switch off level. The pump will also prevent the water level in the upstream basin from dropping below a minimum level to prevent damage in this basin.

I would suggest the following:

1. **Discharge direction** is derived from the connected edges
2. The user defines if the **primary control** is upstream ('drainage pumps') or downstream
3. For **primary upstream control** the user defines upstream switch on (high) and switch off (low) levels. The user also defines the maximum allowable downstream water level that should stop the pump.
4. For **primary downstream control** the user defines downstream switch on (low) and switch off (high) levels. The user also defines the minimum allowable upstream water level that should stop the pump.

**Comment by DanielTollenaar** [comment]
@BdGraaff, think we all agree on the function of most Pumps (and inlets) in the comments above. We also know pumps need switch-on and switch-off levels to function and that these are explicitly implemented in some hydraulic model software (e.g. SOBEK).

I still think in Ribasim (WRM) we can simplify things by the proposal of the (optional) parameters in static-tables mentioned here: https://github.com/Deltares/Ribasim/issues/1771#issuecomment-2317590908.

If you want to go for the advanced solution RIBASIM, including switch-on and switch-off; all is possible using discrete-control the way you are doing right now. That won't change.

**Comment by BdGraaff** [comment]
@DanielTollenaar okay now I see what you mean. Pumps always discharge unless the water level upstream is too low or the water level downstream is too high.

We just tried it out with a simple explicit Excel calculation with a 4 basins. The basins are connected by drainage pumps (red) and one irrigation pump (green). The inlet (a) is for irrigation purposes. This is de model scheme:
![image](https://github.com/user-attachments/assets/f5d382ee-8f1d-4400-92fe-9b6df98a8623)

We tried situations with excess water and situations with water demand. And we get the control we want with the proposed implementation for all situations that we evaluated. The only thing is that we have to balance pump level settings (min_upstream_level and max_downstream_level) for irrigation pumps and drainage pumps that are connected to the same basin. But that is something we would have to do anyway with the discrete control we were using. So we are happy if this can be implemented!
