### ISSUE TITLE
Significant water level differences between development build and 2024.11 release

### ISSUE THREAD

**Issue by rbruijnshkv** [Deltares/Ribasim#1949]
On Monday, 18th November, I received the development build of Ribasim from @visr. This version is required for our work on the Peelvenen project as it includes the newly incorporated step limiter function, which can handle varying Q(h)-relations.

However, upon comparing the results of this development build with the released 2024.11 version, significant differences in water levels were observed when a basin is connected to a Manning Resistance node.

The observed effect indicates that the resistance of the node seems to have increased, resulting in higher water levels upstream. However, no changes were made to the resistance values in the model.

[Peelvenen.zip](https://github.com/user-attachments/files/17869910/Peelvenen.zip): (a part of) the Peelvenen model.

[Differences_in_water_level.pdf](https://github.com/user-attachments/files/17870036/Differences_in_water_level.pdf): a visual analysis of the seen differences. The left column includes the results of the development version. The right column is the released 2024.11 version.

Reach out if there are any questions!

**Comment by SouthEndMusic** [comment]
This might not be due to the step limiter. We (I) have made a few changes to the Manning resistance node in the past few months. The current behavior can be found in the documentation.

The changes are related to what the flow is when the head difference is close to 0. The original expression as derived by @Huite had stability problems in that region.

**Comment by rbruijnshkv** [comment]
As demonstrated in the Ribasim-NL stand-up this morning, the recent changes in the Manning Resistance node also impact the LHM models. After closer inspection, these changes primarily occur in the interaction between the 'doorgaande' and 'bergende' nodes, with only a handful of instances affecting the relation between different polders.

To ensure correct schematization, the water levels in basins connected by a Manning Node need to be nearly identical. Currently, this is not the case. Potential solutions I’ve considered include:

- Lowering the Manning n value of the affected nodes.
- Decreasing the length value of the Manning nodes.

However, these adjustments result in a head difference close to 0. Is this an acceptable approach with the current Ribasim version? Are there more elegant or practical solutions to overcome this issue? What is your view on this?

**Comment by visr** [comment]
> the water levels in basins connected by a Manning Node need to be nearly identical

This to me confirms @SouthEndMusic's idea that https://github.com/Deltares/Ribasim/pull/1750 is responsible for this difference, since that change only affects cases where the water level difference is within 1 mm. We need this change, because otherwise the water levels can start oscillating. So I think either proposed solution is a good way to address this.
