### ISSUE TITLE
Python API docs are broken

### ISSUE THREAD

**Issue by Hofer-Julian** [Deltares/Ribasim#216]
At the time as I create this issue, our API [docs](https://deltares.github.io/Ribasim/python/reference/Basin.html#ribasim.Basin) look like this:

![image](https://github.com/Deltares/Ribasim/assets/30049909/5aea8c4a-ec31-4546-9aa7-7e3828bd394f)

I haven't checked yet, but I think that the latest quartodoc [release broke](https://github.com/machow/quartodoc/releases/tag/v0.3.0) that.

Tasks:

- [ ] Investigate whether moving back to 0.2.2 fixes things
- [ ] Pin the dependency
- [ ] Revert https://github.com/Deltares/Ribasim/pull/201

**Comment by visr** [comment]
It seems that a large part of this issue is us not following the numpydoc conventions properly.

This is after some minor adjustments to the docstrings in #217.

![image](https://github.com/Deltares/Ribasim/assets/4471859/8fc44994-45cb-4518-a587-1ab8af0bf164)

The main issue with this is that quartodoc wants to create a table out of the parameters sections, and putting a list in a parameter description is not rendering as such. I could move the column listings to a separate notes section, though I probably prefer to remove them. We document all table schemas in the usage sections. Perhaps we can insert links to that from the docstring.

**Comment by Hofer-Julian** [comment]
>  though I probably prefer to remove them. We document all table schemas in the usage sections. Perhaps we can insert links to that from the docstring.

Sounds good to me
