### ISSUE TITLE
remove storage from Basin / profile

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#225]
This week we were discussing the "Basin / profile" table with @Hofer-Julian and @SouthEndMusic, and @SouthEndMusic mentioned that having all 3 of storage, area and level is overdetermined. This can lead to profiles that don't have any physical representation. Like the example we use:

https://github.com/Deltares/Ribasim/blob/a10e0d0e2bcb95905d53b04da75eea73f6bc18cc/python/ribasim_testmodels/ribasim_testmodels/basic.py#L70-L72

There a storage of 1000 means an area of 1000 and level of 1. When the level goes to 0, it is not possible that both the area and the storage go down to 0 linearly. Either the area stays constant (vertical walls), such that the storage can go to 0 linearly, or if the area goes linearly to 0 then the storage changes more per centimeter level change near the top since the area is larger there.

In the code we look up both the level and area based on the storage. The storage of the profile can be removed from the table, since we can calculate it ourselves during model initialization by integrating the area (m2) over the level (m) to get storage (m3). I think storage is the most logical one to leave out since level and area are more easily measured, and easier to imagine.

I think it's good to keep supporting models that don't use level at all (by not using node types that use level). For those use cases they can interpret level as a relative number only used to describe the profile and start the bottom at 0 or any other number.

https://deltares.github.io/Ribasim/core/usage.html#basin-profile

**Comment by gijsber** [comment]
I am not 100% sure I agree that we can derive volume from the area and level. Why? the level is located at the basin outlet, while the area represents the waterbody surface for the entire basin (polygon) and the level upstream in the basin may be different than the level at the outlet.

**Comment by Hofer-Julian** [comment]
I am not sure if I fully understand what you mean @gijsber.
The storage should be determined by the following equation, with $S$ being the storage, $A$ being the area and $h$ being the water level:

$$
S = \int_0^{h_{max}} A(h) dh
$$

We have $h(x)$ and $A(x)$ with $x$ being the variable of the linear interpolation given by the user: https://deltares.github.io/Ribasim/core/usage.html#basin-profile. So we have to integrate stepwisely, for each interval given by the user.

That should give us everything to calculate the storage as far as I can see. Please let me know if I've got something wrong here.

**Comment by gijsber** [comment]
Hi @Hofer-Julian when you apply this interpolation method you are indeed right since you determine the volume increment based on the level-increment. Then it does not really matter whether the h is local at the outlet or average over the basin.

**Comment by SouthEndMusic** [comment]
I also think you have to use the average level for this storage integral, otherwise you need a lot more information to obtain the storage, like the gradient in the level and the geometry of the basin.

Say that some data points for the level and the area are given: $(h_i,A_i)$ for $i = 1,2,\ldots n$, where the $h_i$ are ordered. Then the linearly interpolated area function is given by

$$
A(h) = A_i + (A_{i+1}-A_i)\frac{h-h_i}{h_{i+1}-h_i}, \quad \text{for  } h \in [h_i,h_{i+1}).
$$

The storage corresponding to these data points is then given by

$$
S_{i+1} = \int_b^{h_{i+1}} A(h)\text{d}h =  \int_b^{h_i} A(\ell)\text{d}h +  \int_{h_i}^{h_{i+1}} A(h)\text{d}h = S_i +  A_i(h_{i+1}-h_i) + \frac{1}{2}(A_{i+1}-A_i)(h_{i+1}-h_i).
$$

If we assume $b=h_1$ then $S_1=0$, otherwise the storage at the lowest level data point has to be known.

Now you can interpolate linearly using these storage levels, but it is more accurate to use the integration to obtain a piecewise quadratic relationship:

$$
S(h) = S_i + \int_{h_i}^h A(h) \text{d}h = S_i +  A_i(h-h_i) + \frac{1}{2}(A_{i+1}-A_i)\frac{(h-h_i)^2}{h_{i+1}-h_i}
$$

Or inversely:

$$
h(S) = h_i + (h_{i+1}-h_i)\frac{\sqrt{A_i^2+2\frac{A_{i+1}-A_i}{h_{i+1}-h_i}(S-S_i)}-A_i}{A_{i+1}-A_i}, \quad \text{for } S \in [S_i,S_{i+1}).
$$
