### ISSUE TITLE
validation of inputs

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#24]
Enable validation of input:
- [ ] rules
- [ ] API
- [ ] code implementation
- [ ] documentation

**Comment by evetion** [comment]
So implement on both levels:
- Internal data structures
- But also in our "blessed" (GraphML?) external format

**Comment by visr** [comment]
This looks interesting for validating Arrow tables: https://github.com/beacon-biosignals/Legolas.jl/. It is used in https://github.com/beacon-biosignals/LegolasFlux.jl/.

**Comment by evetion** [comment]
- [ ] Check whether extra keys will throw an error

**Comment by gijsber** [comment]
for this moment we can have data struct duplications (julia, plugin, python)
if we introduce rules, you want to have it better organized
at this moment keep validation in julia ~3d (complexity we may need to touch the structs that affect computation)
for future revisit if we want to move to Rust

**Comment by evetion** [comment]
Ok, so ideally, we generate a schema (jsonschema) from a single source, and use that in all other code. For me, that looks like:

Julia -> Jsonschema -> Python / QGIS

The main reason is because Julia has to be able to compute with the input, so it has to be compatible there.

One can [generate Pydantic BaseModels in Python from jsonschemas](https://docs.pydantic.dev/datamodel_code_generator/). These can be [used in Pandera](https://pandera.readthedocs.io/en/stable/pydantic_integration.html) as well, although it might be slower. There's an open issue for Pandera to directly [generate Pandera models from jsonschema](https://github.com/unionai-oss/pandera/issues/421), feel free to upvote it.
