### ISSUE TITLE
tutorial + example script to build a model

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#25]
- [ ] create some basic data (e.g. in shape and CSV formats) to build a model
- [ ] create an example script in python to build the model from this data
- [ ] turn into a tutorial (e.g. jupyter notebook)

Note: this example script should be sufficient input for HKV to build a model from DAMO 2.2

**Comment by evetion** [comment]
- [ ] Have a subsystem in/from arrow open in QGIS and show how to run it.
- [ ] Python script to show waterbalance results.
- [ ] PyArrow to interface into pandas
- [ ] Get external data (any) to update system and run it

**Comment by visr** [comment]
Since we want to show such an example in Python, I created the [ribasim-python](https://github.com/Deltares/ribasim-python) repository (currently still empty), to have a canonical place that we can maintain these tools, available as a package. In the future I see [hydromt_ribasim](https://github.com/Deltares/hydromt_ribasim) using this package to more easily talk to Ribasim.jl as well, e.g. creating inputs in the right formats and such.

**Comment by gijsber** [comment]
I created #55 for those tools

**Comment by visr** [comment]
Ribasim.jl docs needs to link also to the examples: https://github.com/Deltares/ribasim-python/tree/main/examples
