### ISSUE TITLE
Show control in QGIS

### ISSUE THREAD

**Issue by SouthEndMusic** [Deltares/Ribasim#301]
The QGIS plugin has to be updated to display control properly. See how it is plotted now in Ribasim python for consistency. What has to be added:

- [x] Make a distinction between flow edges and control edges (in terms of color) (#335) 
- Also show listen edges

**Comment by evetion** [comment]
- [ ] Support control output file

**Comment by evetion** [comment]
Disccused visualised listen_node_id edges with @visr.

There's no straightforward solution, we either:
- Add a geometry field to the `Control / logic` table, but this violates the special cases of Node/Edge as the only spatial tables.
- Add these edges to the `Edge` table, but since we support multiple listen_node_ids, and require the listen_variable we duplicate this connection data.
- Visualize the control network with a special action button, making a (hidden?) layer that is separate from the input file.

Thinking about this, I have a slight preference for the first.
