### ISSUE TITLE
Speed up large model

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#419]
As far as I can see this is now a valid large model with only static inputs. It should run quickly, but currently takes many hours. Depending on the solver settings it reaches an instability. So we need to investigate why this happens, and do some profiling to see where it spends most time.

Old version: https://github.com/d2hydro/lhm-ribasim/tree/main/models/ribasim_model_nederland
Modified version (profile starts at area 0, Manning become Linear):
- https://github.com/visr/ribasim-artifacts/releases/download/v0.6.0/nl.toml
- https://github.com/visr/ribasim-artifacts/releases/download/v0.6.0/nl.gpkg

**Comment by visr** [comment]
Some initial things I learned:
- taking the median in dudt is a bad idea, fix in #437
- writing output seems to take a long time, in particular the LZ4 compression, we should look into that
- the lookups in the TabulatedRatingCurve are frequent and relatively expensive, look into that
- Euler steps along fine with small dt until it reaches an instability
- ImplicitEuler is very slow, a full Ribasim.run (with output writing) takes 192s for a 1s simulation with 1s timestep.

For the latter, a profile shows almost all time is in LU factorization on a fresh cache, during a linear solve. I assume during successive solves this becomes cheaper. A 10s run (10x longer) takes 6.4 times longer, so partially true. The rest of the time is more running `water_balance!` as part of `jacobian_finitediff_forward!`. We should consider providing [jacobians](https://docs.sciml.ai/DiffEqDocs/stable/features/performance_overloads/#performance_overloads) or looking into autodiff, and looking into linear solver [options](https://docs.sciml.ai/DiffEqDocs/stable/features/linear_nonlinear/#linear_nonlinear).

**Comment by visr** [comment]
The [advanced_ode_example](https://docs.sciml.ai/DiffEqDocs/stable/tutorials/advanced_ode_example/) tutorial is a good guide here. I tried `Symbolics.jacobian_sparsity` but our `water_balance!` does not like Symbolics at all, see https://github.com/Deltares/Ribasim/commit/c319c6ff9c00db2faaa44d47c8dc9f270a75da90 for the attempt.

But since our problem is so sparse that is a good avenue to explore. We did the same using ModelingToolkit.

**Comment by Huite** [comment]
Some thoughts / speculation:

* It's not very surprising that the explicit method encounters instabilities. It would be nice to have some diagnostics like fluctuation size (or something) from every node. But I'm not sure how easy this is to extract from DifferentialEquals.jl.
* Since we're not providing a jacobian prototype, I suppose it's allocating a dense matrix? So if the network has something like 8000 nodes, it's working on an 8000 by 8000 dense matrix.
* It's probably doing a direct solve (via the LU decomposition you've profiled), which has O(n^3) complexity versus O(n^1.5) or O(n^2) for the sparse form.
* I don't exactly understand how the sparsity prototype work, but it's obviously what our sparsity looks like: make a graph of basin to basin connections and turn it into a sparse CSC Matrix.
* These matrices are still pretty small (about 8000 unknowns). I've read that for less than 10 000 to 100 000 unknowns that direct solvers are often faster. This is nice: the direct solver will give an exact answer and we don't have to worry about choosing the right preconditioner. (E.g. HEC-RAS also uses PARDISO, which is direct.)

We can do some experimentation, I think ideally using the network topology of the national model. Then we just write some functions calling DiffEq.jl, where we only solve the unknowns. That might be useful developer documentation anyway!

* Maybe to start, create a (nearly) fully linearized model. E.g. either only linear connections, or just two points on the rating curves.
* We can benchmark what difference giving the a dense versus sparse jacobian prototype makes.
* We can benchmark how much difference automatic differentation versus finite difference versus analytical jacobian makes.
* We can do some benchmarking with Krylov / iterative methods, just as a sanity check.

**Comment by Huite** [comment]
Oh yeah, in terms of homework, don't forget:

https://github.com/ctkelley/NotebookSIAMFANL

**Comment by Hofer-Julian** [comment]
> writing output seems to take a long time, in particular the LZ4 compression, we should look into that

LZ4 is the fastest compression at the moment. We could tweak the level though.

**Comment by visr** [comment]
Nice analysis. 2.6M rows is realistic for a large model, 1600 nodes and 1600 timesteps.

Looking at the [Arrow.jl defaults](https://github.com/apache/arrow-julia/blob/f8d2203b07380e1423723b5bfe32356aa1239284/src/Arrow.jl#L88-L104) I see we currently we use lz4 level 4. Lz4 level 3 would be a bit faster to write and effectively the same size. But zstd level 6 is both significantly smaller and faster to write than that. Based on this graph I'd say let's go with zstd level 6 by default.

People tend to save many runs, so file size matters. If you do analysis on the results you tend to read much more often than you write however, and I believe zstd is slower to read than lz4. Is it possible to add a plot with read speed instead of write speed?

Of course, we could at some point offer this to be configured in the TOML, but picking a good defaults matters.

**Comment by evetion** [comment]
Ha, in the context of this issue I expected you would choose speed, taking the 30% extra filesize for granted.

I have a PR in the works to set the compression and level in the toml.

**Comment by evetion** [comment]
![compression_read](https://github.com/Deltares/Ribasim/assets/8655030/11480ef0-26b1-471b-ab24-16e48309f435)

Read speeds. Note that the uncompressed arrow at 1.79GB is by far the fastest (<1s), at least on my ssd. The graph gives the same results as the write, zstd at l6 and lz4 at l1 seem fine.

**Comment by visr** [comment]
> Maybe to start, create a (nearly) fully linearized model. E.g. either only linear connections, or just two points on the rating curves.

> It's probably doing a direct solve (via the LU decomposition you've profiled), which has O(n^3) complexity versus O(n^1.5) or O(n^2) for the sparse form.

Synthetic models are easier to investigate than the model above since a lot is happening and a lot can be going wrong. [This model](https://github.com/Deltares/Ribasim/issues/9#issuecomment-1607082712) from @SouthEndMusic is great for this test since it is only Basin and LinearResistance nodes. I ran it a few times with different number of basins and indeed I get exactly O(n^3) scaling, going from 0.12 hours for 4 basins to 1649 hours for 400 basins. That is using the TOML below:

<details><summary>TOML</summary>
<p>

```toml
starttime = 2020-01-01 00:00:00
endtime = 2021-01-01 00:00:00
geopackage = "basin_grid.gpkg"

[solver]
algorithm = "ImplicitEuler"
adaptive = false
dt = 1.0
```

</p>
</details> 

| basins | hours |
| ------ | ----- |
| 4      | 0.12  |
| 16     | 0.66  |
| 36     | 2.5   |
| 64     | 7.5   |
| 100    | 17    |
| 196    | 62    |
| 400    | 1649  |

**Comment by evetion** [comment]
Nice time machine you've got there.

**Comment by SouthEndMusic** [comment]
Using the `jac_prototype` (https://github.com/Deltares/Ribasim/pull/459) I get this:

| basins | hours |
| ------ | ----- |
| 4      | 0.14  |
| 16     | 0.38  |
| 36     | 0.83 |
| 64     | 1.33 |

which looks promising. However, for larger numbers of basins I could not get a good indication because the ETA kept shifting.

**Comment by visr** [comment]
That's a great improvement! It still looks slow for so few basins, but it is using 1 second fixed timesteps for 1 year, which is a lot (31e6). So we should merge the sparsity PR, and see from there, also checking the national model in the top post again.

**Comment by visr** [comment]
After running the national model with #459, it now runs! One year ran in 10 minutes. The results seem plausible, with many of the larger basins not yet reaching dynamic equilibrium at the end. A profile now shows that the linear solve time is reduced from 90% to 10% due to the sparsity, which is great progress. What remains is 50% `jacobian_finitediff_forward`. Providing analytic jacobians will hopefully help here. Other speedups can come from optimizing our `water_balance!` function, like the dictionary lookups.

Using a fixed dt fails even with sub-second timesteps, giving "Newton steps could not converge and algorithm is not adaptive. Use a lower dt." It would be nice if we could get this model to work with say fixed hourly timesteps. We should try several things:

- [ ] use [NLNewton(max_iter=100)](https://docs.sciml.ai/DiffEqDocs/stable/features/linear_nonlinear/) instead of the default 10
- [ ] get insight into how large the changes are during the Newton steps
- [ ] change from `abstol=1e-6` to `abstol=1e-3`, or try other values of both tolerances
- [ ] provide analytical jacobians
- [ ] get insight into the effect of replacing piecewise linear functions like TabulatedRatingCurve and Basin / profile with smooth functions

**Comment by visr** [comment]
The estimated results with the now default `jac=true` and `sparse=true` options now look much better:

| basins | hours |
| ------ | ----- |
| 4      | 0.14  |
| 16     | 0.3  |
| 36     | 0.66 |
| 64     | 1 |
| 100     | 1.5 |
| 196     | 3.3 |
| 400     | 9 |

Since the test model is moving to a steady state, the amount of work that needs to be done over time is constantly reducing. Therefore these estimates, which are from say 20s into the run, are larger than actual runtime. Still it provides a useful indication.

Since large models are in a much better state now, I'll close this issue. We still need to work more on performance, but more specific issues with the performance label will be more helpful, I'll create a few follow ups, #452 is one of them.
