### ISSUE TITLE
Add icon to ribasim.exe

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#585]
Can be done using https://github.com/electron/rcedit

```
$ rcedit "path-to-exe-or-dll" --set-icon "path-to-ico"
```

Probably needs a .ico, right now we only have a .png: https://github.com/Deltares/Ribasim/blob/v2023.08.0/qgis/icon.png
EDIT: see favicon.ico in https://github.com/Deltares/Ribasim-NL

This would be an improvement over
![image](https://github.com/Deltares/Ribasim/assets/4471859/b52ffac6-6045-4bec-a924-a42340d32055)

**Comment by Jingru923** [comment]
I was looking into it. Since our binaries are built and released continuously in pipeline. Does it mean we need to somehow add rcedit to our project and do `$ rcedit "path-to-exe-or-dll" --set-icon "path-to-ico"` every time we build our binary in pipeline?

If that is the case, does it mean that we need to add some C/C++ file to our pipeline or project?

**Comment by Jingru923** [comment]
This looks good! :) 

![Image](https://github.com/user-attachments/assets/4e4f11fc-a3a7-4bf0-adb6-058f8534e6ed)

**Comment by visr** [comment]
Nice! Yes we need this every time. If possible not only in TeamCity but in a pixi task.

**Comment by Jingru923** [comment]
Ok, is it okay that rcedit.exe is checked into our repo? @visr

**Comment by Huite** [comment]
It's on conda-forge: https://github.com/conda-forge/rcedit-feedstock

So just add it as a pixi dependency. Make sure it's only on windows.

```toml
[target.windows]
rcedit = "*"
```
