### ISSUE TITLE
Write QGIS style to GeoPackage

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#610]
Currently the Ribasim QGIS plugin applies styling to the layers on loading a model.

It would be nice if we could get the styling information out of the plugin and into the GeoPackage itself so users can start with only Ribasim Python to build a model from skratch and inspect the network. 

That way the plugin does not need to be used for a good looking label. QGIS supports saving styling information to the GeoPackage. I think this is QGIS specific, and not sure how/if the GeoPackage spec says anything about it (it seems not).

It's worth looking into if we can get ribasim-python to write this information to the GeoPackage.

**Comment by deltamarnix** [comment]
I would prefer not to remove the code, as you never know if you receive old files that don't contain the styling. And at the same time, if you want to update your styling with a new release of your plugin, wouldn't you want your geo files to be updated automatically as well? If you save the information in the package, they are stuck there.

**Comment by visr** [comment]
Here a QML style for 'Basin / area' styling by @DanielTollenaar, with graduated semi transparent blues.

[basin_area.qml.txt](https://github.com/Deltares/Ribasim/files/14556959/basin_area.qml.txt)

**Comment by visr** [comment]
> If you save the information in the package, they are stuck there.

True, but we currently only support using the set of components together for the same Ribasim release. We may support upgrading models in the future, and if we do this we could decide to upgrade the style as well.

**Comment by Huite** [comment]
Is the styling part of any official specification? It's probably quite stable since changing it would break people's styling made with older QGIS versions.
I just know that I made the terrible decision in the past to try and generate a QGIS project file directly as an XML, and we found out the hard way that they aren't stable at all.

By the way, I don't think you'd want to remove the code from the plugin: whether you setup a model in QGIS or via ribasim-python, you want styling in both cases. Inside the plugin, the most straightforward way is to set it up as is works now, but **then** export it to the geopackage as styling.

In ribasim-python, you're always forced to generate the XML yourself.

**Comment by visr** [comment]
In https://www.geopackage.org/extensions.html there is the [Styling and Symbology Extension](https://gitlab.com/imagemattersllc/ogc-tb-16-gpkg/-/blob/master/extensions/5-portrayal.adoc). Though the fact that that is an archived repository with a notice "This subsection is under discussion and may change radically." is not very reassuring.

But probably if we do this we may still want to have an option in Ribasim Python and/or the QGIS plugin to reset the style to the current Ribasim style. We just store it in the GeoPackage to have a better user experience for non-plugin users, and to give them more freedom to modify the style and retain that.
