### ISSUE TITLE
fiona ImportError in Ribasim environment

### ISSUE THREAD

**Issue by d2hydro** [Deltares/Ribasim#612]
I use `mamba-forge` to build en environment with the [environment.yml](https://github.com/Deltares/Ribasim/blob/main/environment.yml). Now importing Fiona will cause an ImportError:

![image](https://github.com/Deltares/Ribasim/assets/43996424/06acb91a-fafa-44c6-8237-dcff2d06054c)

I know I can get a working `fiona` if I do not use the [channel: conda-forge](https://github.com/Deltares/Ribasim/blob/c1932949f06b736a93a2b1a42679fa671fa4a7cd/environment.yml#L3C1-L4). However, in this case it will result in an unsolvable environment, starting with `pyogrio`.

Please advise

**Comment by visr** [comment]
Installing environments like this will break from time to time, there is little we can do other than excluding certain versions in the `environment.yml` whenever this happens. This is a part of the reason we moved to https://pixi.sh/, since we can just check in a working pixi.lock file such that everyone uses exactly the same version. I recommend you try it out.

**Comment by visr** [comment]
This was also an issue when using `pixi run python` and `import fiona`. The cause was having `c:\OSGeo4W\bin` in the PATH, which interferes with the GDAL we want to use.
