### ISSUE TITLE
numbering of nodes

### ISSUE THREAD

**Issue by JvanHouwelingen** [Deltares/Ribasim#694]
Maybe this comment is related to the issue "stability of node and edge IDs". 

I try to change my basis model following from the lumping tool within a python script to avoid changing my model manually in Qgis each time my basis model is changing with newer versions of the lumping/volume tools.

One of my actions is to remove isolated basin nodes (not connected to other nodes). However, when you remove a node from your model.node.static geodataframe the model is not valid anymore. The validation test is based on the number of nodes and a continues numbering of nodes, which means that no numbers may be skipped. If I would rearrange my numbering of the nodes, my edges definitions are no longer correct as well. Is it possible to keep the numbering as is, also when nodes are removed?

**Comment by visr** [comment]
Thanks for the input. Indeed this is related to #682 To fix this, I think we should directly just remove the validation rule as suggested in https://github.com/harm-nomden-sweco/ribasim_lumping/issues/64#issuecomment-1771091793. That is an easy fix for the direct issue, #682 could be a follow up.

**Comment by visr** [comment]
This actually isn't that easy, since we currently assume in the `graph` and `flow` that the node ID and index are one and the same. So we'd need to add a mapping from node ID to index, and go through that mapping instead of directly using e.g. `inneighbors(graph, id)`. I don't think a sparse matrix from 1 to max_node_ID is a real option, since that could get `typemax(Int)` big.
