### ISSUE TITLE
Iterative coupling Modflow-Ribasim

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#7]
Requires aquifer Q-h relationship.

Try a complete version with all piecewise linear relations
Try a fully linearized version

**Comment by Huite** [comment]
This requires alternative input for the basin. 

Arguably, the easiest option is to add two additional columns to the basin forcing. These are:

* hydraulic head [m]
* conductance [m2/d] or resistance [d], or rather in [m2/s] and [s]!

These form an additional boundary condition, and are mostly a replacement for the infiltration and drainage column (but need not be). Standalone, they might not see too much use, but we expect them to work well for the coupling. Rather than have a single value for the entire stress period, Ribasim is able to increase or reduce infiltration or drainage more intelligently, so the coupled iterations should converge faster.

One of the question is whether we should use conductance or resistance (with conductance = cross_section_area / resistance). The cross-sectional area could depend on the water level of Ribasim, but for the coupling with MODFLOW, the conductance is likely the easiest to I'm tending to conductance instead.

Another reason to pick conductance rather than resistance is that conductance is very much a model parameter, rather than a resistance, which looks like a parameter with a clear physical meaning (the hydraulic resistance of the bed) but depending on which head you choose is actually a lot more complicated (a lumped effective resistance, integrating many flow paths in the basin).

**Comment by Huite** [comment]
These are the water balance equations:

```
if level > head
