### ISSUE TITLE
Determine subnetwork shortage(supply)/excess(drainage) condition in timestep

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#79]
Control actions may be different when you are in a shortage/supply state of an excess/discharge state.

A method is needed to determine on a subnetwork whether the system is for this subnetwork in a supply or drainage situation, such that proper controll settings can be triggered
part of #14. Links to #349

**Comment by gijsber** [comment]
from @SouthEndMusic 
#79 is nog wel relevant in dat mijn huidige aanpak nog geen rekening houdt met supply vanuit een subnetwork. Ik zie nog niet direct voor me hoe dat kan worden toegevoegd, anders dan een soort iteratieve koppeling tussen hoofdnetwerk en subnetwerken, maar dat zou waarschijnlijk heel slecht zijn voor performance

**Comment by gijsber** [comment]
Before calculating the main network allocation, you first do a subnetwork allocation. That calculation propagates demands to the sources. If that same calculation could be tweeked to calculate the outflow at the sinks without any water coming from the sources (ie the excess water which the subnetwork wants to dump on the main network), you might have the information you need

**Comment by SouthEndMusic** [comment]
Collecting subnetwork demand is added in https://github.com/Deltares/Ribasim/pull/964. Currently an excess of water in a subnetwork is ignored as discussed with @gijsber; this yields zero demand from the subnetwork. The excess water in the subnetwork is not used anywhere else (e.g. in the main network or a different subnetwork via the main network), as this would complicate the allocation algorithm with more optimization problems for the exchanged water. Control as mentioned in the issue is covered by https://github.com/Deltares/Ribasim/issues/714.

**Comment by SouthEndMusic** [comment]
> Before calculating the main network allocation, you first do a subnetwork allocation. That calculation propagates demands to the sources. If that same calculation could be tweeked to calculate the outflow at the sinks without any water coming from the sources (ie the excess water which the subnetwork wants to dump on the main network), you might have the information you need

@gijsber as discussed, we are currently not interested in using a surplus of water in a subnetwork. However, if at some point we would want to do this, I think it would look like this: do a last optimization after all priorities in a subnetwork, where connections from the subnetwork back to the main network have unlimited demand. This way this optimization is incentivized to bring as much of the surplus water back to the main network as possible.
