### ISSUE TITLE
Check validation doc page rendering

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#902]
After #896 was merged I looked at https://deltares.github.io/Ribasim/core/validation.html and saw nice tables and hidden code cells. A few commits on main later I only see the code and no tables.

**Comment by SouthEndMusic** [comment]
@Hofer-Julian we need your magical presence again ✨️

**Comment by SouthEndMusic** [comment]
I believe the only additional requirement to make it work is IJulia

**Comment by Hofer-Julian** [comment]
This is really weird.

This is the correct output the CI produced at https://github.com/Deltares/Ribasim/commit/aa243c8cbca648449ce004b053e2c26b7b7faeec:

```

[29/38] core/validation.qmd

Starting julia-1.10 kernel...Done

Executing 'validation.ipynb'
  Cell 1/2...Done
  Cell 2/2...Done
```

This is what it produced for the commit afterwards https://github.com/Deltares/Ribasim/commit/641758f2145d6db39ed2f0dd360fd36f5ff9f59f:

```
Starting python3 kernel...0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Done
```

For some reason, it now boots up a python3 kernel rather than a julia kernel.

**Comment by Hofer-Julian** [comment]
We could work around it, by using a Jupyter notebook directly, rather than a qmd
