### ISSUE TITLE
conflict packages between ribasim and ribasim-lumping

### ISSUE THREAD

**Issue by JvanHouwelingen** [Deltares/Ribasim#909]
[see same issue in ribasim-lumping]
There seems to be a conflict between the Ribasim and Ribasim-lumping dependencies.

The Ribasim loc file indicates a version of "dask>=2022.7" should be installed.
For Ribasim-lumping the "dfm_tools" package should be installed, which depends on "copernicus-marine-client", for which "dask>=2022.1.1, <2023.0.0" should be installed. 

After installing my environment. I observe that dask is installed with version "2022.12.1". This is allowed following above constraints. However, this "dask" version gives me the following error when importing Ribasim in my script:
AttributeError: module 'pandas.core.strings' has no attribute 'StringMethods'

This error is solved when updating my dask package to a version >2023, but this is not allowed for the dfm_tools package which is required for ribasim-lumping.

Because of this conflict I cannot manage my environment and run my script.

**Comment by evetion** [comment]
Thanks for making an issue!

Our pixi _lock_ file should only be used for developing Ribasim itself, not in use with other packages (as it has been not resolved with other packages in mind). For use with other packages, a pip install should be enough. The Ribasim python package itself only [depends on pandas](https://github.com/Deltares/Ribasim/blob/main/python/ribasim/pyproject.toml), without a version specified. That might be a bit too loose, but it should work fine together with dfm_tools (which does restrain the pandas and dask versions).

If you do want to make use of the ribasim pixi environment, you can run `pixi run pip install dfm_tools`, which should work (and creates a new lock file, probably with dask>=2023).

**Comment by JvanHouwelingen** [comment]
Thank you for your quick response. 

Within the company we use poetry as a package manager.
I started with installing Ribasim (v0.6.1) as a python package (just poetry add ribasim works fine). "import ribasim" in a python script within this poetry environment won't give errors. So, on itself it works.

Ribasim lumping depends on a specific version of hydrolib-core, which I got from Harm last week. I added hydrolib-core by adding a local path to this hydrolib-core version. Not very clean, but I should use this version. 

Next step would be adding the ribasim-lumping package. However, poetry does not support requirements.txt and the requirements.txt seems to be outdated (ribasim=0.2.0). That's why I added the ribasim-lumping code to the source of my "local" environment. In this way I could import ribasim-lumping into my script and add the required packages manually (step-by-step). The packages ipykernel, xarray and xugrid are added subsequently without problems. A conflict arises when adding dfm_tools package. dfm_tools depends on the "copernicus-marine-client", for which "dask>=2022.1.1, <2023.0.0" should be installed. However, ribasim requires dask>2023.0.0.

If I downgrade dask to a version < 2023 (e.g. 2022.12.1), the ribasim package itself fails when importing in a script, with the following error: AttributeError: module 'pandas.core.strings' has no attribute 'StringMethods'.

For now the depencies wihtin my environment are:
[tool.poetry.dependencies]
python = "^3.10"
ribasim = "^0.6.1"
hydrolib-core = {path = "../Ribasim/HYDROLIB-core"}
ipykernel = "^6.27.1"
xarray = "^2023.12.0"
xugrid = "^0.8.0"
networkx = "^3.2.1"
dask = ">=2023.0"

Ribasim can be imported, ribasim-lumping fails because of missing dfm_tools. Could it be that poetry is to strict?

**Comment by evetion** [comment]
Note that poetry can use git urls directly: `poetry add git+https://github.com/Deltares/HYDROLIB-core.git`, including specifying branches etc. See https://python-poetry.org/docs/cli/#add. This will work with setup.py or pyproject.toml directly and ignores the requirements.txt.

That said, it still won't work, since all these packages are all slightly incompatible with one another. The main issue here is with ribasim-lumping, which [pins the versions](https://github.com/harm-nomden-sweco/ribasim_lumping/blob/main/setup.py) of the packages it uses, probably causing some conflicts, as Ribasim itself doesn't depend directly on dask, only on pandas. I would advise to relax the bounds of ribasim-lumping (by forking/editing) and see where that gets you, while discussion it [in the other issue](https://github.com/harm-nomden-sweco/ribasim_lumping/issues/82).

I'm gonna close this issue, but will follow any activity in ribasim-lumping.
