### ISSUE TITLE
QGIS: Remove checkboxes from dataset widget

### ISSUE THREAD

**Issue by deltamarnix** [Deltares/Ribasim#916]
**What?**
The checkboxes in the dataset widget in QGIS don't seem to have a function. When we look in code, there seems to be no connection to these checkboxes.

**Why?**
The interface is cluttered and the user may be confused on what these checkboxes might do. Especially in combination with the buttons underneath (Add to QGIS, Remove from Dataset). These buttons work with the selection instead.

**How?**
Make them simple list view items without a checkbox.

**Comment by Huite** [comment]
These checkboxes are a remnant from the Tim plugin where they do serve a function: you can use them to turn boundary conditions on or off. This concept doesn't exist in Ribasim since things are also represented in the network so the different input layers are not additive.

The checkboxds should be removed indeed.
