### ISSUE TITLE
Reorganize documentation to become more modeller oriented

### ISSUE THREAD

**Issue by gijsber** [Deltares/Ribasim#973]
**What:**
- Reorganize the home page to become a better entry point for modellers.
- Add a Concepts page to provide a more elaborate explanation of the concepts.

**Why**
the current documentation has a strong developer and technical reference orientation (=good), but lacks a conceptual introduction.

**How**

- [ ] reorganize home page https://deltares.github.io/Ribasim/ into table of contents:

- introduction
- Conceptualization (physical-control-allocation layer)
- Development planning
- About the code
- Downloads

- [ ] add https://deltares.github.io/Ribasim/concepts page. Table of contents:

- Water balance in time & space
- Control concepts
- Equations
- Allocation

Respective related tasks:
- [ ] move section 3 of https://deltares.github.io/Ribasim/ to Concepts page
- [ ] add descriptive section
- [ ] move water balance equations from https://deltares.github.io/Ribasim/core/equations.html to Concepts page
- [ ] add descriptive explanation including sequence digram of nested allocation
- [ ]  move Allocation section from https://deltares.github.io/Ribasim/core/allocation.html to Concepts page

**Comment by gijsber** [comment]
Parking lot for the sequence diagram explaining the nested allocation and interaction with the main loop

```mermaid
sequenceDiagram

participant boundary
participant basin
participant user
participant allocation_subNetwork
participant allocation_mainNetwork

user->>allocation_subNetwork: demand
par
   allocation_subNetwork-->>allocation_mainNetwork: demand inventory at inlets
end
boundary->>allocation_mainNetwork: source availablility
basin->>allocation_mainNetwork: source availablility
allocation_mainNetwork-->>allocation_mainNetwork: allocate to inlets
allocation_mainNetwork->>allocation_subNetwork: allocated
par
   allocation_subNetwork-->>allocation_subNetwork: allocate to users
end
allocation_subNetwork->>user: allocated
user->>basin: abstracted
```

**Comment by visr** [comment]
> Parking lot

Just to be clear, make sure you keep the mermaid syntax. In Quarto we use this rather than a PNG render, see https://github.com/Deltares/Ribasim/blob/605e5b9b20eea77cd29ab3f39f06f7bfe6933571/docs/core/index.qmd#L15-L39.

**Comment by gijsber** [comment]
No worries, if you go to edit mode in the comment you get the mermaid syntax for both figures. Github does the rendering to a picture

**Comment by gijsber** [comment]
### Conceptual differences with other model codes
**Ribasim 9 versus Ribasim 7**
Ribasim 7 is a heuristic water allocation model where prioritized water demands are met from preferential sources such as inflows or surface water reservoirs (i.e. dams). Nodes in the network typically do not have a storage component (except for reservoir nodes or natural lakes). typical timesteps therefore are 10-day, by-monthly or monthly as this allows a drop of water to reach the end of the network within the timestep. Ribasim 7 allows flow direction in one-way only (ie downstream), while demands can be propagated upstream to reservoirs or diversions. Ribasim 7 allows various formulations to compute water demand for agriculture or plublic water supply, while it also offers a reservoir node with hydropower oriented operations. The water distribution is primarily derived by matching source availability with demands given reservoir rules (flood control-target and firm levels) and hedging rules) local flow-based control options for diversions and bifurcations.
Ribasim 9 deviates from this paradigm as its water balance is not driven by a demand-allocation matching algorith. Instead it is driven by a numerical scheme that solves the water balance equation for a chain of basins (buckets) with storages which are connected by elements that determine the flow exchange between the basins based on Qh-relations, resistance (i.e. a head difference) or control rules. This numerical scheme chooses its internal timestepping. Compared to Ribasim 7, Ribasim 9 allows much more flexibility to define control rules. Ribasim 9 also deviates on the allocation paradigm as its allocation algorithm primarily is focussed on deciding where water abstractions need to be reduced - in the rule-based simulation - to keep sufficient water in the system for high-prioirity users.
Also in terms of water demand, Ribasim 9 deviates from Ribasim 7, as the kernel is given a user/abstraction demand, either via a preprocessed timeseries, or via an online coupling with other models (e.g. unsaturated zone or groundwater models).
**Ribasim 9 versus D-Hydro**

**Comment by SouthEndMusic** [comment]
> This is my suggestion for the update of the Home page (https://deltares.github.io/Ribasim/)

I like it, I do have some comments:

Notes:

- 'either by controlling the inflow or outflow, or by controlling a water level'. We do support level control by PID control or discrete control, but we do not support flow control (other than setting flow rates directly by aforementioned control mechanisms). Trying to control flow lead to some nasty bugs and conceptual problems.
- Regarding the first figure of the allocation layer: updating a setpoint is an interesting one. It is not especially dificult to do, but I do want to point out that this is conceptually different from what control has done upto this point, because updating a setpoint of discrete control changes the control rules themselves. We have to think about validation rules for this.
- 'and the rule-based simulation will determine the actual abstraction.' I think this is conceptually easiest to understand, but:
1. Whether a user can abstract depending on the level of the abstraction basin is handled with reduction factors in the physical layer
2. Basin target levels are yet to be properly implemented in allocation (https://github.com/Deltares/Ribasim/issues/564)
- Regarding the second figure:
1. As discussed with @visr, users are also allowed to be part of the main network directly. It is a matter of what we think is clearer whether we include this in the figures or whether it is mentioned in text only.
2. In case 'par' stands for parallel: in theory these processes can be done in parallel (if JuMP/Highs indeed also support this), but in practice this is not yet done. We should have a technical discussion with @visr and/or @Hofer-Julian about what is required to support this, and whether for instance the Julia tests can still be run in parallel if the tests themselves run parallel processes.
